name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'main'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: az container list --resource-group AIfinalProject
      - run: docker login tomerfinalprojectai.azurecr.io -u tomerfinalprojectai -p ${{ secrets.ACR_PASSWORD }}
      - run: echo "yoyo"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
              push: true
              tags: tomerfinalprojectai.azurecr.io/projectimage:latest
      - run: docker images
      - run: echo "yoyo"