name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'main'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "yoyo"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build no push
        uses: docker/build-push-action@v5
        with:
              push: false
              load: true
              tags: shimon/abc
      - run: docker images
      - run: echo "yoyo"